import {
  CodeXml,
  Menu,
  X,
  Sun,
  Moon,
  ArrowRight,
  Users,
  Languages,
  Hammer,
  Sparkles,
  Puzzle,
  Shapes,
  FileCode2,
  Globe,
  Server,
  Rocket,
  ChevronRight,
  TerminalSquare,
  Globe2,
  Bot,
  BrainCircuit,
  Smartphone,
  Gamepad2,
  Cake,
  BookOpen,
  FolderKanban,
  LayoutTemplate,
  Send,
  GraduationCap,
  TrendingUp,
  Cpu,
  Sprout,
  MessageSquareCode,
  User,
  LayoutDashboard,
  Camera,
  PlayCircle,
  Link2,
  type LucideIcon,
} from "lucide-react";

export const icons = {
  "code-xml": CodeXml,
  menu: Menu,
  x: X,
  sun: Sun,
  moon: Moon,
  "arrow-right": ArrowRight,
  users: Users,
  languages: Languages,
  hammer: Hammer,
  sparkles: Sparkles,
  puzzle: Puzzle,
  shapes: Shapes,
  "file-code-2": FileCode2,
  globe: Globe,
  server: Server,
  rocket: Rocket,
  "chevron-right": ChevronRight,
  "terminal-square": TerminalSquare,
  "globe-2": Globe2,
  bot: Bot,
  "brain-circuit": BrainCircuit,
  smartphone: Smartphone,
  "gamepad-2": Gamepad2,
  cake: Cake,
  "book-open": BookOpen,
  "folder-kanban": FolderKanban,
  "layout-template": LayoutTemplate,
  send: Send,
  "graduation-cap": GraduationCap,
  "trending-up": TrendingUp,
  cpu: Cpu,
  sprout: Sprout,
  "message-square-code": MessageSquareCode,
  user: User,
  "layout-dashboard": LayoutDashboard,
  // lucide-react dropped brand/logo icons (trademark reasons); these are the
  // closest generic stand-ins for the prototype's Instagram/YouTube/LinkedIn links.
  instagram: Camera,
  youtube: PlayCircle,
  linkedin: Link2,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function Icon({
  name,
  ...props
}: { name: IconName } & React.ComponentProps<LucideIcon>) {
  const Component = icons[name];
  return <Component {...props} />;
}
